# -*- coding: utf-8 -*-
"""approximation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DvDo9zSR38mKdWLwyoXB3B6hdM8zH01y
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install tikzplotlib

import numpy as np
import matplotlib.pyplot as plt
import tikzplotlib

rng = np.random.default_rng(seed=42);

samples = 1000000
N = 20
bins = np.arange(-0.5, N + 2.5, 1)
density = True

p = np.array([0.01, 0.05, 0.1, 0.15, 0.5, 0.9, 0.99])

fig, axs = plt.subplots(2, p.size, figsize=(22, 5));

for i in range(p.size):
  # Generate samples from the binomial distributions
  sample = rng.binomial(N, p[i], size=samples)

  # Approximate binomial distribution
  mu = (N - 1) * p[i]
  sigma = np.sqrt((N - 1) * p[i] * (1 - p[i]))
  #normalSample = np.clip(np.floor(np.random.normal(mu, sigma, samples)) + 1, 1, N)
  normalSample = np.clip(np.floor(rng.normal(mu, sigma, samples)), 0, N) + 1 # Deliot et al.
  pOneSuccess = 1 - pow(1 - p[i], N)
  gating = rng.random(samples) > pOneSuccess
  approximation = np.where(gating, 0, normalSample)

  # Plot
  axs[0,i].hist(sample, bins, density=density, alpha=1.0, color='orange', edgecolor='darkorange')
  axs[0,i].hist(approximation, bins, density=density, alpha=0.5, color='purple', edgecolor='rebeccapurple')


  normalApproximation = np.clip(rng.normal(N * p[i], np.sqrt(N * p[i] * (1-p[i])), size=samples), 0, N)

  axs[1,i].hist(sample, bins, density=density, alpha=1.0, color='orange', edgecolor='darkorange')
  axs[1,i].hist(normalApproximation, bins, density=density, alpha=0.5, color='green', edgecolor='darkgreen')

tikzplotlib.save("approximation.tikz")
plt.show()