# -*- coding: utf-8 -*-
"""blending.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OOQLphmVipzC9mUy9lpKWy00WNEv4tFd
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install tikzplotlib

import numpy as np
import matplotlib.pyplot as plt
import tikzplotlib

rng = np.random.default_rng(seed=42);

p = 0.5
samples = 10000
n0 = 6
n1 = 60
w = 0.4
n = (1-w) * n0 + w * n1
bins = np.arange(-0.5, 45.5, 1)
density = True

# Generate samples from the binomial distributions
sample0 = rng.binomial(n0, p, size=samples)
sample1 = rng.binomial(n1, p, size=samples)
sampleTrue = rng.binomial(n, p, size=samples)

# Plot
plt.hist(sample0, bins, density=density, alpha=0.3, color='orange', edgecolor='darkorange')
plt.hist(sample1, bins, density=density, alpha=0.3, color='orange', edgecolor='darkorange')
plt.hist(sampleTrue, bins, density=density, alpha=1.0, color='orange', edgecolor='darkorange')
plt.xlabel('Number of Successes')
plt.ylabel('Probability')
tikzplotlib.save("blending-reference.tikz")
plt.show()

sampleLinear = (1-w) * sample0 + w * sample1

# Plot
plt.hist(sample0, bins, density=density, alpha=0.3, color='orange', edgecolor='darkorange')
plt.hist(sample1, bins, density=density, alpha=0.3, color='orange', edgecolor='darkorange')
plt.hist(sampleTrue, bins, density=density, alpha=1.0, color='orange', edgecolor='darkorange')
plt.hist(sampleLinear, bins, density=density, alpha=0.8, color='lightsteelblue', edgecolor='steelblue')
plt.xlabel('Number of Successes')
plt.ylabel('Probability')
tikzplotlib.save("blending-linear.tikz")
plt.show()

sampleDistributed = rng.binomial((1-w) * n0, p, size=samples) + rng.binomial(w * n1, p, size=samples)

# Plot
plt.hist(sample0, bins, density=density, alpha=0.3, color='orange', edgecolor='darkorange')
plt.hist(sample1, bins, density=density, alpha=0.3, color='orange', edgecolor='darkorange')
plt.hist(sampleTrue, bins, density=density, alpha=1.0, color='orange', edgecolor='darkorange')
plt.hist(sampleDistributed, bins, density=density, alpha=0.8, color='mediumpurple', edgecolor='rebeccapurple')
plt.xlabel('Number of Successes')
plt.ylabel('Probability')
tikzplotlib.save("blending-distributed.tikz")
plt.show()