# -*- coding: utf-8 -*-
"""performance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DIRSBBKolECzerdyhdNpC1Ljg6eoioJi
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install tikzplotlib
# Fix for dashing
from matplotlib.lines import Line2D
from matplotlib.legend import Legend
Line2D._us_dashSeq    = property(lambda self: self._dash_pattern[1])
Line2D._us_dashOffset = property(lambda self: self._dash_pattern[0])
Legend._ncol = property(lambda self: self._ncols)

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import tikzplotlib

resolutions = np.array([
    1614*1211,
    826*933,
    553*660,
    547*360,
    721*774,
    1193*1059,
    955*775,
    2604*1841,
    2604*1540,
    1329*1562,
    2376*1785,
    1920*1009,
    1600*829,
    2732*1987,
    1620*1622,
])
ggx = np.array([
    0.33, 0.12, 0.05, 0.04, 0.08, 0.21, 0.11, 0.40, 0.34, 0.36, 0.33, 0.33, 0.22, 0.37, 0.45
])
glints = np.array([
    4.24, 3.06, 1.87, 1.10, 2.72, 3.55, 3.13, 4.09, 3.86, 4.35, 3.62, 4.34, 4.40, 4.06, 4.17
])

# sort
idx = np.argsort(resolutions)
resolutions = resolutions[idx]
ggx = ggx[idx]
glints = glints[idx]


fig, (ax1, ax2) = plt.subplots(2, figsize=(8, 5), sharex=True)
ax2.set_xlabel("Resolution in total pixel count")
ax1.set_ylabel("Performance in ms")
ax1.yaxis.set_units("ms")
ax2.set_ylabel("Relation to GGX")
ax1.yaxis.set_major_formatter(ticker.FormatStrFormatter('%dms'))
ax2.yaxis.set_major_formatter(ticker.FormatStrFormatter('$%d\\times$'))

ax1.plot(resolutions, glints, color='purple', marker='.', label="Glints")
ax1.plot(resolutions, ggx, color='blue', marker='.', label="GGX")
ax1.legend()

ax2.plot(resolutions, glints / ggx, color='orange', marker='.')
#ax2.axline((0,10), slope=0, color='darkorange', linestyle="--")
ax2.plot([resolutions[0], resolutions[-1]], [10, 10], color='darkorange', linestyle="--")

fig.tight_layout()
#tikzplotlib.clean_figure(fig)
tikzplotlib.save("performance.tikz")
plt.show()